# Generated by Django 5.0.4 on 2024-04-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.CharField(max_length=30)),
                ('c2', models.CharField(max_length=200)),
                ('c3', models.CharField(max_length=200)),
                ('c4', models.CharField(max_length=200)),
                ('c5', models.CharField(max_length=200)),
                ('c6', models.CharField(max_length=200)),
                ('c7', models.CharField(max_length=200)),
                ('c8', models.CharField(max_length=200)),
            ],
        ),
    ]
